# travis-ci.org - continuous testing environment - http://docs.travis-ci.com/

language: c
compiler:
  - gcc
  - clang

# The build machines are Ubuntu 12.04 x64
addons:
  apt:
    packages:
      - initscripts
      - libc-bin
      - libgd2-xpm-dev
      - libgeoip-dev
      - libxslt1-dev
      - libpcre++0
      - libpcre++-dev
      - liblua5.1-0-dev
      - libssl-dev
      - lua5.1
      - openssl
      - passwd
      - libperl-dev

# TODO: fix tests so they don't depend on /usr/local/nginx/logs/
#       so we can run `make`, `make test`, `make install`.

script:
  - ./configure --enable-mods-static=all --with-ipv6 --with-http_v2_module
  - make -j2
  - sudo make install
